%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\mmpsy\AppData\Local\Temp\Evaluation_PARTICIPANT_SESSION_2023-04-27_19h27.47.771.csv
%
% Auto-generated by MATLAB on 12-May-2023 13:33:18

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 36);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["width", "height", "subject_nr", "avatar_file", "gender", "other_ratee", "block_nr", "rater_name", "rater_file", "ratee_type", "ratee_name", "ratee_file", "liking", "trial_nr", "positive_left", "positive_correct", "pos_word", "neg_word", "correct_word", "left_word", "right_word", "response", "choice", "chose_positive", "accuracy", "comment", "t_start_experiment", "t_start_block", "t_start_trial", "t_response", "likes_on_left", "evaluation", "t_ask_eval", "t_eval_resp", "rater_avatar", "ratee_avatar"];
opts.VariableTypes = ["double", "double", "double", "double", "categorical", "string", "double", "categorical", "string", "categorical", "categorical", "double", "categorical", "double", "double", "double", "string", "string", "string", "string", "string", "double", "string", "categorical", "categorical", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["other_ratee", "rater_file", "pos_word", "neg_word", "correct_word", "left_word", "right_word", "choice", "comment", "ratee_avatar"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["gender", "other_ratee", "rater_name", "rater_file", "ratee_type", "ratee_name", "liking", "pos_word", "neg_word", "correct_word", "left_word", "right_word", "choice", "chose_positive", "accuracy", "comment", "ratee_avatar"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["avatar_file", "ratee_file", "rater_avatar"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["avatar_file", "ratee_file", "rater_avatar"], "ThousandsSeparator", ",");

% Import the data
EvaluationPARTICIPANTSESSION2023042719h27 = readtable("C:\Users\mmpsy\AppData\Local\Temp\Evaluation_PARTICIPANT_SESSION_2023-04-27_19h27.47.771.csv", opts);


%% Clear temporary variables
clear opts